apiVersion: v1
kind: ServiceAccount
metadata:
  name: robot-controller
  namespace: cloud-robotics
  labels:
    app: robot-controller
automountServiceAccountToken: true
---
# export TOKEN=$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)
# export NAMESPACE=$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace)
# export CERT=$(cat /var/run/secrets/kubernetes.io/serviceaccount/ca.crt)
# wget --no-check-certificate --header "Authorization: Bearer $TOKEN" https://$KUBERNETES_SERVICE_HOST/apis/ -O-apiVersion: rbac.authorization.k8s.io/v1
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: robot-controller
  labels:
    app: robot-controller
rules:
  - apiGroups:
     - ""
    resources:
      - ResourceAll
      - '*'
    verbs:
      - VerbAll
      - '*'
  - apiGroups:
      - apps
    resources:
      - ResourceAll
      - '*'
    verbs:
      - VerbAll
      - '*'
  - apiGroups:
     - "batch"
    resources:
      - ResourceAll
      - '*'
    verbs:
      - VerbAll
      - '*'
  - apiGroups:
      - networking.k8s.io
    resources:
      - ResourceAll
      - '*'
    verbs:
      - VerbAll
      - '*'
  - apiGroups:
      - fulfil.ai
    resources:
      - ResourceAll
      - '*'
    verbs:
      - VerbAll
      - '*'
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: robot-controller
  labels:
    app: robot-controller
roleRef:
  kind: ClusterRole
  name: robot-controller
  apiGroup: rbac.authorization.k8s.io
subjects:
  - apiGroup: ""
    kind: ServiceAccount
    name: robot-controller
    namespace: cloud-robotics